### DISCUSSION TITLE
Github action node js version

### DISCUSSION THREAD

**Discussion by dongokovacs** [nodejs/help#4910] [Q&A] [answered]
Hi ,

A tri to run github action
with yml:

```yaml
on:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    runs-on: windows-latest # or macos-latest, windows-latest, ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '14'

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npx playwright install

      - name: run tests
        run: npm run cicd

      - name: push artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            playwright-report/**
            test-results/**
          if-no-file-found: error
          retention-days: 60
```

But i get this message:
Run npx playwright install
You are running Node.js 10.2[4](https://github.com/daniavander/hydro-test/runs/5376226594?check_suite_focus=true#step:5:4).1.
Playwright requires Node.js 12 or higher. 
Please update your version of Node.js.
Error: Process completed with exit code 1.

Can u help me pls?

**Comment by aduh95** [comment, marked as answer]
Replace

```
  - uses: actions/setup-node@v1
```

with

```
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
```

That would tell the runner to install the latest available Node.js LTS version, which is almost certainly what you need here.
