### ISSUE TITLE
React frontend working on port 443 with nginx proxy but backend springboot is not woking on port 443 even though ssl is installe on common domain

### ISSUE THREAD

**Issue by gg-gg-v1** [nodejs/help#2710]
* **Node.js Version**: latest
* **OS**: EC2
* **Scope (install, code, runtime, meta, other?)**:configuation
* **Module (and version) (if relevant)**:react, springboot

fronend React working on port 443 with nginx proxy but backend springboot is not woking on port 443 even though ssl is installe on common domain

1. on aws ec2, I have installed ssl with the help of apache httpd dependencies.
2. I have docker-compose file (provided below), basically the docker which is able to run following three applications together. 
2.1 Backend SpringBoot app 
2.2 Frontend REACT app 
2.3 Proxy nginx

docker-compose.yml file
------------------------------------------
```
version: '3'
services:
  # [Backend SpringBoot app]
  springboot-mysql-app:
    container_name: springboot-mysql-app
    image: springboot-mysql-app:latest
    build:
      context: ./springboot-mysql-docker-compose
      dockerfile: Dockerfile
    working_dir: /springboot-mysql-docker-compose
    restart: on-failure
    volumes:
      - ./springboot-mysql-docker-compose:/springboot-mysql-docker-compose
    ports:
      - "9090:8080" # 9090 is the port that I am using in apache virtual host config as proxy and also as a proxy which I am using in nginx as well.
  networks:
      springboot-mysql-network:

  # [Frontend REACT app]
  app-client:
    build:
      context: react-app-client # Use an image built from the specified dockerfile in the `react-app-client` directory.
      dockerfile: Dockerfile
      args:
	REACT_APP_API_BASE_URL: apeoki.com/b:9090
        REACT_APP_WEB_URL: apeoki.com
    ports:
      - "8001:3000"# 8001 is the port that I am using in apache virtual host config as proxy and also as a proxy which I am using in nginx as well.
    restart: always
    depends_on:
      - springboot-mysql-app
    networks:
      springboot-mysql-network:
  # [Proxy nginx]
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8000:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
networks:
    springboot-mysql-network:
------------------------------------------
```

Note: using nginx proxy as mentioned in above docker uses below default.conf file
------------------------------------------
```
server{
    listen 443;

    # [Frontend REACT app  proxy config], this is working fine able to see LOCK ICON with HTTPS
    location / {
        proxy_pass          http://localhost:8001;
        proxy_set_header    X-Real-IP   $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto http;
        proxy_set_header    Host    $http_host;
        client_max_body_size 17m;
        proxy_http_version  1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header    Connection "upgrade";
    }

    # [Backend SpringBoot app proxy config], this is not working fine not able to see https
    location /b {
        rewrite ^/b(.*) $1 break;
        proxy_pass          http://localhost:9090;
        proxy_set_header    X-Real-IP   $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto http;
        proxy_set_header    Host    $http_host;
        client_max_body_size 17m;
        proxy_http_version  1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header    Connection "upgrade";
    }
}
```
3. Below is the content of my ssl config file, here also I am using proxy,
 with this ProxyPass, "" ProxyPass /  http://localhost:8001/"" 
 I am able to run the frontend react app.

my apache conf file localion and content below: /etc/httpd/conf.d/ssl.conf
```
<VirtualHost *:443>

# General setup for the virtual host, inherited from global configuration
#DocumentRoot "/var/www/html"
ServerName http://apeoki.com
ProxyPass         /b  http://localhost:9090/
ProxyPassReverse  /b  http://localhost:9090/
ProxyPass         /  http://localhost:8001/
ProxyPassReverse  /  http://localhost:8001/
RequestHeader set X-Forwarded-Proto https
RequestHeader set X-Forwarded-Port 443
ProxyPreserveHost On

</VirtualHost>
```
4. I do have apache AJP proxy(provided below) in springboot.
```
    @Bean
    public TomcatServletWebServerFactory servletContainer() {

        TomcatServletWebServerFactory tomcat = new TomcatServletWebServerFactory();

        Connector ajpConnector = new Connector("AJP/1.3");

        ajpConnector.setPort(9090);
        ajpConnector.setSecure(false);
        ajpConnector.setAllowTrace(false);
        ajpConnector.setScheme("https");
        ((AbstractAjpProtocol) ajpConnector.getProtocolHandler()).setSecretRequired(false);
        tomcat.addAdditionalTomcatConnectors(ajpConnector);

        return tomcat;
    }
```
My concern:
I am able to run the frontend app on https://apeoki.com but not able to open the link https://apeoki.com/startupIdeas, because path '/startupIdeas' internally calls the backend springboot service ('http://apeoki.com:9090/getStartupIdeasListPageByPage/1/20') which is http only not https even though I have already installed SSL on the EC2 and domain apeoki.com is pointing to ec2 ip.
not sure why https is not working even though I have already install SSL certificate.
domain is common and ssl is installed still why this kind of behaviour ?
Not sure what's wrong in my configurations.

attaching the screenshot also for internal springboot calling from react app.

Can you please help ? I have struggled a lot for this but no luck.

I know I have provided too much of configuration details so that it will make picture clear in front of you.
<img width="1318" alt="Screenshot 2020-05-17 at 10 21 57 PM" src="https://user-images.githubusercontent.com/7572667/82156017-637eeb80-9896-11ea-8a26-16ab3bf68a7b.png">
